# Generated by Django 5.0.4 on 2024-05-27 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproject', '0002_alter_category_name_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(default='Новость', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posttype', to='djangoproject.category'),
        ),
    ]
